public enum Tematica {
    GENERALIDADES, FILOSOFIA, PSICOLOGIA, RELIGION, CIENCIAS_SOCIALES, LENGUAS, CIENCIAS_MATEMATICA, TECNOLOGIA, ARTES, LITERATURA, GEOGRAFIA, HISTORIA;
    //Asociaciones
    public Repositorio repositorio;
}
